name: graph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - git
  - cmake
  - ninja
  - make
  - cxx-compiler
  - pkg-config
  - cython
  - numpy
  - scipy
  - networkx
  - requests
  - pandas
  - scikit-learn
  - tqdm
  - psutil
  - packaging
  - pyyaml
  - torchinfo
  - setuptools
  - wheel
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu126
      - torch
      - torchvision
      - torchaudio
